### ISSUE TITLE
Weird handling of array in XSD

### ISSUE THREAD

**Issue by ghilainm** [andrewbober/xsd2jsonschema#11]
Seems like arrays defined in XSD generate weird content.
*Input*
```
 <xs:element name="SomeField" minOccurs="0" maxOccurs="9" type="SomeType">
 </xs:element>
```
*Output*
```
        SomeField:
          oneOf:
            - $ref: '#definitions/SomeType'
            - type: array
              maxItems: 9
              items:
                $ref: '#definitions/SomeType'
```
For me it should not use oneOf for arrays. I should only be the second entry of the oneOf without oneOf.

**Comment by ghilainm** [comment]
Seems like you are right, this should be like you defined it. Sorry for opening the issue :). Just didn't get the XSD syntax!

**Comment by ghilainm** [comment]
I would like to reopen this because what is generated is not really convenient for the Java generator from OpenAPI. Wouldn't it be simpler to generate only this:

```
        SomeField:
            - type: array
              maxItems: 9
              items:
                $ref: '#definitions/SomeType'
```
