### ISSUE TITLE
Wrong handling of root element

### ISSUE THREAD

**Issue by ghilainm** [andrewbober/xsd2jsonschema#12]
It seems like the handling of the root element is not correct.

Here is the xsd
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http:/xxx">
  <!--==========================================================-->
  <!--===== Root Element                                        -->
  <!--==========================================================-->
  <xs:element name="MyMessage" type="MyMessageType" />
  <!--==========================================================-->
  <!--===== Root Element Content                                -->
  <!--==========================================================-->
  <xs:complexType name="MyMessageType">
    <xs:sequence>
      <xs:element name="myField" type="xs:string">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

```

Here is the generated json
```
definitions:
    MyMessage:
      $ref: "#/definitions/MyMessageType"
    MyMessageType:
      type: object
      properties:
        myField:
          type: string
      required:
        - myField
```

Here is the expected generated json
```
definitions:
    MyMessage:
      type: object
      properties:
        myField:
          type: string
      required:
        - myField
```
